spring.datasource.url=jdbc:h2:file:./data/wiperdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

jwt.secret=66546A555E5A7234753778214123222A472D4B614E645262356B587032733576
JWT_ACCESS_TOKEN_DURATION_MINUTE=60
JWT_ACCESS_TOKEN_DURATION_SECOND=3600
JWT_REFRESH_TOKEN_DURATION_DAY=7
JWT_REFRESH_TOKEN_DURATION_SECOND=604800
JWT_ACCESS_COOKIE_NAME=access_token
JWT_REFRESH_COOKIE_NAME=refresh_token
upload.path=C:/Projects/uploads